version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    security-updates-only: true
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    security-updates-only: true
    schedule:
      interval: "daily"
