version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    security-updates-only: true
    schedule:
      interval: daily
      time: "07:30"
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: org.springframework.boot:spring-boot-starter-parent
      versions:
      - "> 2.2.0.RELEASE"
      - "< 2.4.0"
  - package-ecosystem: "docker"
    directory: "/" # Location of package manifests
    security-updates-only: true
    schedule:
      interval: daily
      time: "07:30"
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: azul/zulu-openjdk
      versions:
      - "> 11.0.1"
      - "< 12.0.0"
